version: '2'
services:
  jhipstertest9-app:
    image: jhipstertest9
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstertest9-postgresql:5432/jhipstertest9
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jhipstertest9-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhipstertest9-elasticsearch:9200
    ports:
      - 8080:8080
  jhipstertest9-postgresql:
    extends:
      file: postgresql.yml
      service: jhipstertest9-postgresql
  jhipstertest9-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhipstertest9-elasticsearch
